apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-hellogo
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-hellogo
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-hellogo
    spec:
      containers:
      - name: {{.Release.Name}}-hellogo
        image: {{.Values.image.repository}}:{{.Values.image.tag}}
        ports:
        - containerPort: {{.Values.port}}
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
