apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-hellogo
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Values.image.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.name }}
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: {{.Values.image.repository}}:{{.Values.image.tag}}
        ports:
        - containerPort: {{.Values.port}}
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
